---
title: "Predicting Salmon Returns"
subtitle: "A survey of existing models and an exploration of new methods for building better predictions"
author: "<br>2024 WA-BC-Idaho AFS Joint Meeting"
date: "Monday, April 29, 2024"
output:
  html_document:
    fig_caption: yes
    theme: cerulean
    toc: no
    toc_depth: 3
    toc_float: yes
---

```{r set_options, echo=FALSE, cache=FALSE}
options(width = 100)
```

***

## Instructors

[**Dr. Matt Falcy**](https://www.uidaho.edu/cnr/faculty/falcy)   
Assistant Unit Leader | Idaho Cooperative Fish and Wildlife Research Unit  
Assistant Professor | Department of Fish and Wildlife Sciences  
University of Idaho  

[**Dr. Mark Scheuerell**](https://fish.uw.edu/faculty/mark-scheuerell/)   
Assistant Unit Leader | Washington Cooperative Fish and Wildlife Research Unit  
Associate Professor | School of Aquatic and Fishery Sciences  
University of Washington  

***

## Schedule & Topics

Links to materials are included after each topic. (Note: Use the arrows keys to navigate through HTML versions of materials.)

### Session 1 - Traditional Approaches

__8:00 - 9:40__ 

  * Introductions 

  * Forecasting overview | [slide deck](session_1/forecasting_overview.html)
  
  * Model complexity, selection & evaluation | [slide deck](session_1/SalmonForecasting_ModelComplexitySelectionEvaluation.pptx) | [R exercise (LOOCV)](session_1/LOOCV.R) | [R exercise (Overfitting)](session_1/Overfitting.R)

### Break

__9:40 - 10:00__

### Session 2 - Contemporary Approaches

__10:00 - 12:00__

  * State-Space Models | [slide deck](session_2/intro_to_SSMs.html) | [R exercise (SSM)](session_2/fitting_ssm.html)
  
  * Integrated Population Models | [slide deck](session_2/intro_to_IPMs.html)
  
  * Risk-adverse decision making | [slide deck](session_2/SalmonForecasting_DecisionMaking.pptx)
  
<br><br>


 

